---
title: "Assignment2"
author: "Raphael Stolpe"
date: "9/23/2019"
output: html_document
---

```{r setup, include=FALSE}
## 0. Install and load packages
#library(XML)
#library(rcdk)
#library(rJava)
#install.packages("WikidataQueryServiceR")
library(WikidataQueryServiceR)
library(Metrics)
```

```{r query}


# 1. Query for Alkanes in wikidata: get boilingpoint with units and smiles for each molecule
query <- 'SELECT ?comp ?compLabel ?bp ?bpUnit ?bpUnitLabel ?CC WHERE {   ?comp wdt:P31/wdt:P279* wd:Q41581 ;   wdt:P233 ?CC ;     p:P2102 [         ps:P2102 ?bp ;           psv:P2102/wikibase:quantityUnit  ?bpUnit         ] .   SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". } } '

r <- query_wikidata(query)

# control for boilingpoint units: convert all to kelvin
r$bp[r$bpUnitLabel == "degree Celsius"] <- r$bp[r$bpUnitLabel == "degree Celsius"] + 273.15
r$bpUnitLabel[r$bpUnitLabel == "degree Celsius"] <- "kelvin"
r$bp[r$bpUnitLabel == "degree Fahrenheit"] <- (r$bp[r$bpUnitLabel == "degree Fahrenheit"]-32)*5/9 + 273.15
r$bpUnitLabel[r$bpUnitLabel == "degree Fahrenheit"] <- "kelvin"


```

```{r descriptors}
# 2. Parse smiles and compute descriptors
smiles <- r$CC
parsed_smiles <- parse.smiles(smiles, kekulise=TRUE)

descNames <- c(
'org.openscience.cdk.qsar.descriptors.molecular.WienerNumbersDescriptor',
'org.openscience.cdk.qsar.descriptors.molecular.APolDescriptor',
'org.openscience.cdk.qsar.descriptors.molecular.AtomCountDescriptor'
)

descs <- eval.desc(parsed_smiles, descNames)



```

```{r pls regression}
# 3. Perform pls regression 
library(pls)
library(e1071)
library(graphics)
# 3.1 split dataset into training and testing datasets
data <- data.frame(r$bp, descs)
set.seed(42)
rows <- sample(nrow(data))
data <- data[rows, ]
split <- round(nrow(data)*0.75)

train <- data[1:split, ]
test <- data[(split+1):nrow(data), ]
ytrain <- train$r.bp
ytest <- test$r.bp

# 3.2 Build null model as the mean of all boilingpoints 
nullmodel <- mean(train$r.bp)
errorNM <- rmse(test$r.bp, nullmodel)

# 3.3 Train pls regression model
#mdl <- plsr(train$r.bp ~ (apol + khs.ssCH2 + khs.sCH3 + khs.sssCH + nHBDon), data = train, ncomp = 5, validation = "LOO")
mdl <- plsr(train$r.bp ~., data = train, validation = "CV")
error <- RMSEP(mdl, estimate = "CV", newdata = test)
predicted <- predict(mdl, test)
error.pred <- rmse(predicted, ytest)
plot(mdl$residuals)
## Visualization
# plot predicted against actual values
plot(predicted[,,1], ytest, xlab = "Predicted Boiling Point [K]", ylab = "Measured Boiling Point [K]", main = "Regression with one PC")
plot(predicted[,,2], ytest, xlab = "Predicted Boiling Point [K]", ylab = "Measured Boiling Point [K]", main = "Regression with two PCs")
plot(predicted[,,3], ytest, xlab = "Predicted Boiling Point [K]", ylab = "Measured Boiling Point [K]", main = "Regression with three PCs")
plot(predicted[,,4], ytest, xlab = "Predicted Boiling Point [K]", ylab = "Measured Boiling Point [K]", main = "Regression with four PCs")

# plot error
ncompo <- c(0:4)
plot(ncompo, error$val, type = "p", xlab = "Number of principle components", ylab = "RMSEP [K]",
     main = "RMSE of Prediction against Number of Principle Components")

##### SVM 
svm <- svm(train$r.bp ~., data = train)
predicted.svm <- predict(svm, test)
error.pred <- rmse(predicted.svm, ytest)
```

## Including Plots

# References 

Wiener, H. (1947). Structural Determination of Paraffin Boiling Points. Journal of the American Chemical Society, 69(1), 17–20. https://doi.org/10.1021/ja01193a005
